version: "3.7"
services:
  certbot:
    image: certbot/certbot:latest
    entrypoint: ""
    ports:
      - "80:80"
    command:
      - sh
      - -c
      - "apk add --update nginx && pip install certbot-nginx && certbot \
        certonly \
        --nginx \
        --non-interactive \
        --agree-tos \
        --email moshe@avni.us \
        --domains avni.us --domains www.avni.us"
    volumes:
      - ./data/nginx/nginx.pid:/run/nginx/nginx.pid
      - ./data/nginx/app-init.conf:/etc/nginx/conf.d/app-init.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
