version: "3.7"
services:
  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
    volumes:
      - ./data/nginx/app-init.conf:/etc/nginx/conf.d/app-no-ssl.conf
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on: ["avnius"]

  avnius:
    build: .
    ports:
      - 5000:5000
